#!/bin/bash

## Functions
# Returns 1 or 0, depending on whether the specified program is available.
function exists() { type "$1" >/dev/null 2>/dev/null; }

# Make dd format more conventional.
function dd() { sudo dd bs=4M if=$PWD/${1} of=${2}; }

function um() { udiskie-mount /dev/${@}; }

function uu() { udiskie-umount /dev/${@}; }

function poweroff() {
	read -p "Are you sure you want to shutdown the machine? " -n 1 -r
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
		return 1
	fi

	sudo poweroff
}

function reboot() {
	read -p "Are you sure you want to reboot the machine? " -n 1 -r
	echo    # (optional) move to a new line
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
		return 1
	fi

	sudo reboot
}
