#!/bin/sh
xset r rate 200 75 &
redshift-gtk -l 57:12 &
feh --bg-fill ~/Pictures/background.jpg &

xrdb ~/.Xresources && urxvt -title initTerm -e sh -c screen &
emacs --eval '(server-start)' &
pavucontrol &
chromium &
thunderbird &
nm-applet &
gnome-settings-daemon &
