#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config border_width         4
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 true

bspc rule -a Emacs desktop='^1'
bspc rule -a Firefox-esr desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a mpv desktop='^5' state=floating
bspc rule -a "TeamSpeak 3" desktop='^4'
bspc rule -a Mumble desktop='^4'
bspc rule -a Steam desktop='^5'
bspc rule -a Icedove desktop='^6'
bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a URxvt:sc desktop='^8'

panel&
