#! /bin/sh

sxhkd &

# Create 9 desktops.
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Border width of 4 pixels.
bspc config border_width         4
# No window gap
bspc config window_gap 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config click_to_focus true

# Emacs
bspc rule -a Emacs desktop='^1' state=tiled
bspc desktop 1 -l monocle
# Browser
bspc rule -a Firefox-esr desktop='^2'
bspc rule -a Firefox desktop='^2'
# Communication
bspc rule -a "TeamSpeak 3" desktop='^4'
bspc rule -a Mumble desktop='^4'
# Entertainment & media
bspc rule -a mpv desktop='^5' state=fullscreen
bspc rule -a Google-chrome desktop='^5' state=fullscreen
bspc rule -a Steam desktop='^7'
# E-mail
bspc rule -a Icedove desktop='^6'
bspc rule -a Thunderbird desktop='^6'
# Drawing
bspc rule -a Gimp desktop='^9' state=floating follow=on
# Background terminal
bspc rule -a URxvt:sc desktop='^8'

#panel&
xfce4-panel&
